openapi: 3.0.0
info:
  title: Polygon Notary System
  contact: { }
  version: '1.0'
servers:
  - url: http://localhost:5000/api/v1/polygon/
    variables: { }
paths:
  /send-otp/{email}:
    parameters:
      - in: path
        name: email
        schema:
          type: string
        required: true
        description: Users Email Id
    get:
      tags:
        - Login
      summary: Send Otp
      operationId: SendOtp
      responses:
        '200':
          description: ''
          headers: { }
  /verify-otp:
    post:
      tags:
        - Login
      summary: Verify Otp
      operationId: VerifyOtp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOtp'
        required: true
      responses:
        '200':
          description: ''
          headers: { }
components:
  schemas:
    VerifyOtp:
      title: VerifyOtp
      required:
        - email
        - otp
      type: object
      properties:
        email:
          type: string
        otp:
          type: string
      example:
        email: bob@gmail.com
        otp: 123456